name: vjptest
description: VJP Connect Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 📌 Icons iOS
  cupertino_icons: ^1.0.2

  # 📌 Environment Variables
  flutter_dotenv: ^5.1.0  # Thay thế flutter_config

  # 📌 Networking
  dio: ^5.4.1  # HTTP client mạnh mẽ
  dio_smart_retry: ^7.0.0  # Retry interceptor for Dio
  http: ^1.2.0  # Thêm package http
  http_parser: ^4.0.2  # Hỗ trợ parse HTTP headers

  # 📌 State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  bloc: ^8.1.3  # Core bloc package
  bloc_concurrency: ^0.2.3  # Concurrency utilities for bloc

  # 📌 WebSocket
  web_socket_channel: ^2.4.0  # Hỗ trợ kết nối WebSocket

  # 📌 JSON Parser
  equatable: ^2.0.5  # Hỗ trợ so sánh object trong Bloc
  json_annotation: ^4.8.1  # Chuyển đổi JSON dễ dàng

  # 📌 Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1

  # 📌 Image Upload
  image_picker: ^1.0.7
  cloudinary_public: ^0.21.0  # Upload ảnh lên Cloudinary

  # 📌 UI Components
  share_plus: ^7.2.1  # Share functionality

  # 📌 Others
  shared_preferences: ^2.5.2
  url_launcher: ^6.1.14
  flutter_secure_storage: ^9.0.0  # Secure storage for sensitive data
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.7.0
  salomon_bottom_bar: ^3.3.2
  smooth_page_indicator: ^1.1.0
  go_router: ^13.1.0
  persistent_bottom_nav_bar: ^5.0.2

  # 📌 Internationalization
  intl: ^0.19.0

  # 📌 JWT Decoder
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 📌 Code Linting
  flutter_lints: ^2.0.0

  # 📌 JSON Code Generator
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  encrypt: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/logo1VN.png
    - assets/images/logo3ENG.png
    - assets/images/default_avatar.png
    - assets/images/logo2JP.png
    - assets/images/logoGoogle.jpg