class FormatLanguage {
  static Map<String, Map<String, String>> labels = {
    'vi': {
      'email': 'Email',
      'password': 'Mật khẩu',
      'company': 'Tên Công Ty',
      'fullName': 'Họ và tên',
      'phone': 'Điện Thoại',
      'referral': 'Mã giới thiệu',
      'entity': 'Pháp nhân',
      'package': 'Chọn gói đăng ký',
      'terms': 'Bằng cách nhấp vào Đăng ký, bạn đồng ý với ',
      'termsLink': 'Điều khoản sử dụng',
      'loginButton': 'ĐĂNG NHẬP',
      'registerButton': 'ĐĂNG KÝ',
      'welcome': 'Chào Mừng!',
      'switchToRegister': 'Nếu chưa có tài khoản hãy nhấn nút \'Đăng Ký\'',
      'switchToLogin': 'Nếu đã có tài khoản hãy nhấn nút \'Đăng Nhập\'',
      'basicPackage': 'Gói cơ bản',
      'advancedPackage': 'Gói nâng cao',
      'premiumPackage': 'Gói premium',
      'japanEntity': 'Nhật Bản',
      'vietnamEntity': 'Việt Nam',
      'loginTitle': 'ĐĂNG NHẬP',
      'registerTitle': 'ĐĂNG KÝ',
      'loginSubtitle': 'Đăng nhập để tiếp tục',
      'registerSubtitle': 'Tạo tài khoản mới',
      'emailRequired': 'Vui lòng nhập email',
      'invalidEmail': 'Email không hợp lệ',
      'passwordRequired': 'Vui lòng nhập mật khẩu',
      'passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
      'fillAllFields': 'Vui lòng điền đầy đủ thông tin',
      'acceptTermsError': 'Vui lòng đồng ý với điều khoản sử dụng',
      'invalidPhone': 'Số điện thoại không hợp lệ',
    },
    'en': {
      'email': 'Email',
      'password': 'Password',
      'company': 'Company Name',
      'fullName': 'Full Name',
      'phone': 'Phone Number',
      'referral': 'Referral Code',
      'entity': 'Legal Entity',
      'package': 'Select Package',
      'terms': 'By clicking Register, you agree to our ',
      'termsLink': 'Terms of Use',
      'loginButton': 'LOGIN',
      'registerButton': 'REGISTER',
      'welcome': 'Welcome!',
      'switchToRegister': 'Don\'t have an account? Click \'Register\'',
      'switchToLogin': 'Already have an account? Click \'Login\'',
      'basicPackage': 'Basic Package',
      'advancedPackage': 'Advanced Package',
      'premiumPackage': 'Premium Package',
      'japanEntity': 'Japan',
      'vietnamEntity': 'Vietnam',
      'loginTitle': 'LOGIN',
      'registerTitle': 'REGISTER',
      'loginSubtitle': 'Sign in to continue',
      'registerSubtitle': 'Create new account',
      'emailRequired': 'Please enter your email',
      'invalidEmail': 'Invalid email format',
      'passwordRequired': 'Please enter your password',
      'passwordTooShort': 'Password must be at least 6 characters',
      'fillAllFields': 'Please fill in all required fields',
      'acceptTermsError': 'Please accept the terms of use',
      'invalidPhone': 'Invalid phone number',
    },
    'ja': {
      'email': 'メール',
      'password': 'パスワード',
      'company': '会社名',
      'fullName': '氏名',
      'phone': '電話番号',
      'referral': '紹介コード',
      'entity': '法人',
      'package': 'パッケージ選択',
      'terms': '登録をクリックすることで、',
      'termsLink': '利用規約',
      'loginButton': 'ログイン',
      'registerButton': '登録',
      'welcome': 'ようこそ！',
      'switchToRegister': 'アカウントをお持ちでない方は「登録」をクリック',
      'switchToLogin': 'すでにアカウントをお持ちの方は「ログイン」をクリック',
      'basicPackage': 'ベーシックプラン',
      'advancedPackage': 'アドバンスドプラン',
      'premiumPackage': 'プレミアムプラン',
      'japanEntity': '日本',
      'vietnamEntity': 'ベトナム',
      'loginTitle': 'ログイン',
      'registerTitle': '登録',
      'loginSubtitle': '続けるにはログインしてください',
      'registerSubtitle': '新規アカウント作成',
      'emailRequired': 'メールアドレスを入力してください',
      'invalidEmail': 'メールアドレスの形式が正しくありません',
      'passwordRequired': 'パスワードを入力してください',
      'passwordTooShort': 'パスワードは6文字以上で入力してください',
      'fillAllFields': '必須項目をすべて入力してください',
      'acceptTermsError': '利用規約に同意してください',
      'invalidPhone': '電話番号の形式が正しくありません',
    }
  };

  static String getLabel(String language, String key) {
    return labels[language]?[key] ?? labels['vi']![key]!;
  }
} 